### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by stefanseidler182** [stefanseidler182/viergewinnt#1]
Für den bestehenden Code müssen Unit Tests erstellt werden, die die Spiellogik überprüfen. Auch etwaige Sonderfälle, wie Spielbrett is voll müssen überprüft werden.

**Comment by kakici28** [comment]
Folgende Kriterien müssen unbedingt erfüllt werden:

1. Kann man den Stein spielen?
2. Wer hat gewonnen?
3. Ist das Spielbrett voll?
