### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by stefanseidler182** [stefanseidler182/viergewinnt#2]
Erstellen Sie für alle Klassen, Methoden und Attribute docstring Dokumentation im numpy Standard. Teilweise sind schon Kommentare vorhanden. Bei denen müssen wir schauen, ob Sie im numpy Standard sein.

**Comment by kakici28** [comment]
**Docstrings fertigstellen:**

1. def test_spielstart - tests,py
2. def test_printSpielfeld
3. def printSpielfeld
4. def beenden
5. properties
6. def voll
7. Klassen
