### ISSUE TITLE
Sphinx Doku

### ISSUE THREAD

**Issue by stefanseidler182** [stefanseidler182/viergewinnt#3]
Über den gesamten Source Code und die docstring Dokumentation muss ein Sphinx Doku erstellt. Die Ergebnisse davon sollen nicht ins git Repo geladen werden.

**Comment by kakici28** [comment]
**Folgendes muss noch ergänzt werden;**

1. **test.md**: def test_spielstart muss noch eingefügt und kommentiert werden + Syntax verbessern
2. **design.md** fertigstellen
3. **Readme** bezüglich der Generierung der Sphinx Doku ergänzen (Geht das ohne build ordner überhaupt?)
